name: Lua Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["5.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Set module directory
        id: module
        shell: bash
        run: |
          VERSION="${{ matrix.version }}"
          VER="${VERSION//./}"
          echo "version=${VER}" >> $GITHUB_OUTPUT
      - name: Build Lua dynamic library
        run: make tests-${{ steps.module.outputs.version }}
        shell: bash
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run tests
        run: |
          go test -v ./...
        working-directory: lua${{ steps.module.outputs.version }}
